<a href="https://colab.research.google.com/github/vinay10949/AnalyticsAndML/blob/master/FeatureEngineering/Text/4_TFIDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
# load data
data = fetch_20newsgroups(subset='train')
df = pd.DataFrame(data.data, columns=['text'])
df.head()

Downloading 20news dataset. This may take a few minutes.
Downloading dataset from https://ndownloader.figshare.com/files/5975967 (14 MB)

                                                text
0  From: lerxst@wam.umd.edu (where's my thing)\nS...
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...
2  From: twillis@ec.ecn.purdue.edu (Thomas E Will...
3  From: jgreen@amber (Joe Green)\nSubject: Re: W...
4  From: jcm@head-cfa.harvard.edu (Jonathan McDow...

In [0]:
# remove punctuation and numbers
df['text'] = df['text'].str.replace('[^\w\s]','').str.replace('\d+', '')

In [0]:
# set up Tf-idf transformer
vectorizer = TfidfVectorizer(lowercase=True,
                             stop_words='english',
                             ngram_range=(1, 1),
                             min_df=0.05)

In [5]:
# learn words to be retained and their frequency

vectorizer.fit(df['text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=0.05, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [0]:
X = vectorizer.transform(df['text'])

In [7]:
# create tf-idf dataframe

tfidf = pd.DataFrame(X.toarray(),
                          columns = vectorizer.get_feature_names())

tfidf.head()

   able    access  actually  ago  ...  year    years       yes  youre
0   0.0  0.000000  0.000000  0.0  ...   0.0  0.27302  0.000000    0.0
1   0.0  0.000000  0.000000  0.0  ...   0.0  0.00000  0.000000    0.0
2   0.0  0.135765  0.123914  0.0  ...   0.0  0.00000  0.000000    0.0
3   0.0  0.000000  0.000000  0.0  ...   0.0  0.00000  0.000000    0.0
4   0.0  0.000000  0.000000  0.0  ...   0.0  0.00000  0.264836    0.0

[5 rows x 191 columns]

In [8]:
tfidf.shape

(11314, 191)

In [0]:
# with n grams
vectorizer = TfidfVectorizer(lowercase=True,
                             stop_words='english',
                             ngram_range=(1, 2),
                             min_df=0.1)

In [10]:
vectorizer.fit(df['text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=0.1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [0]:
X = vectorizer.transform(df['text'])

In [12]:
tfidf = pd.DataFrame(X.toarray(),
                          columns = vectorizer.get_feature_names())

tfidf.head()

    article  believe    better  ...    writes  writes article     years
0  0.000000      0.0  0.000000  ...  0.000000        0.000000  0.374196
1  0.000000      0.0  0.000000  ...  0.000000        0.000000  0.000000
2  0.000000      0.0  0.186832  ...  0.000000        0.000000  0.000000
3  0.168872      0.0  0.000000  ...  0.154322        0.301699  0.000000
4  0.329602      0.0  0.000000  ...  0.150602        0.000000  0.000000

[5 rows x 59 columns]

In [13]:
vectorizer.get_feature_names()

['article',
 'believe',
 'better',
 'case',
 'computer',
 'did',
 'distribution',
 'does',
 'doesnt',
 'dont',
 'email',
 'going',
 'good',
 'got',
 'help',
 'im',
 'ive',
 'just',
 'know',
 'like',
 'lines',
 'lines article',
 'lines nntppostinghost',
 'make',
 'need',
 'new',
 'nntppostinghost',
 'organization',
 'organization university',
 'people',
 'point',
 'problem',
 'question',
 'read',
 'really',
 'replyto',
 'right',
 'said',
 'say',
 'state',
 'subject',
 'sure',
 'thanks',
 'thing',
 'things',
 'think',
 'time',
 'university',
 'usa',
 'use',
 'used',
 'using',
 'want',
 'way',
 'work',
 'world',
 'writes',
 'writes article',
 'years']